---
title: "proyecto 1 Notebook"
---

Instalacion de paquetes
```{r}
Sys.setenv(PATH = paste("C:/rtools40/usr/bin;C:/rtools40/ucrt64/bin", Sys.getenv("PATH"), sep = ";"))

Sys.which("make")
install.packages("C:\\Users\\dalca\\Downloads\\db_csv_\\fim4r_1.8\\fim4r", 
repos = NULL, 
type = "source")
install.packages('arules')
install.packages('dplyr')
install.packages("ggplot2")
install.packages("ggalt")

```

Imports
```{r}
library(ggalt)
library(ggplot2)
library(arules)
library(dplyr)
```

Limpieza de los datos
```{r}
data_importacion = read.csv('C:\\Users\\dalca\\Documents\\Usac - Maestria\\2024\\Cursos\\Cuarto Trimeste\\Mineria de datos\\Proyecto 1\\95_2024_4_04_MIICC408_A_Proyecto1\\Datos\\Importaciones.csv', sep=',', fileEncoding = "latin1")

catalogo_continente = read.csv('C:\\Users\\dalca\\Documents\\Usac - Maestria\\2024\\Cursos\\Cuarto Trimeste\\Mineria de datos\\Proyecto 1\\95_2024_4_04_MIICC408_A_Proyecto1\\Datos\\Catalogo Pais-Continente.csv', sep=',' ,fileEncoding = "UTF-8")
catalogo_continente

#Renombrar las columnas
names(catalogo_continente) <- c("Codigo", "COD_CONTINENTE","CONTINENTE", "NOMBRE_PAIS")
#Eliminar la columna 'Extra' 
catalogo_continente <- catalogo_continente[, c("Codigo", "COD_CONTINENTE","CONTINENTE", "NOMBRE_PAIS")]


data_importacion
catalogo_continente

#Unificar la columna de ANYI y MES en una nueva columna
data_importacion <- data_importacion %>%
  mutate(ANYO_MES = paste(ANYO, MES, sep = "-"))

#Eliminar  la columna de ANYO y MES, reorganizar las columnas del set de datos
data_importacion <- data_importacion[, c("ANYO_MES", setdiff(names(data_importacion), c("ANYO_MES","ANYO", "MES")))]

data_importacion = merge(data_importacion, catalogo_continente, by.x = "PAIS", by.y = "Codigo", all.x = TRUE)

sapply(data_importacion, function(x) sum(is.na(x)))

#Corregir los paises sin Catalogo de continentes
data_importacion
data_importacion <- data_importacion %>%
  mutate(
    NOMBRE_PAIS = case_when(
      PAIS == 2603 ~ "2603",
      PAIS == 4229 ~ "4229",
      TRUE ~ NOMBRE_PAIS
    ),
    COD_CONTINENTE = case_when(
      PAIS == 2603 ~ 1,
      PAIS == 4229 ~ 2,
      TRUE ~ COD_CONTINENTE
    ),
    CONTINENTE = case_when(
      PAIS == 2603 ~ "América",
      PAIS == 4229 ~ "Europa",
      TRUE ~ CONTINENTE
    )
  )

data_importacion[is.na(data_importacion$CONTINENTE), ]
sapply(data_importacion, function(x) sum(is.na(x)))

summary(data_importacion)

#Cambio del campo Valor de char a numeric
data_importacion$VALOR <- as.numeric(gsub(",", "", data_importacion$VALOR))
summary(data_importacion)

```

Reglas de asociación Apriori
```{r}

data_importacion
data_importacion_apriori = subset(data_importacion, select = -NOMBRE_PAIS)
reglas_importacion_apriori = apriori(data_importacion_apriori, parameter = list(support = 0.2, confidence = 0.5) )

summary(reglas_importacion_apriori) 

reglas_importacion_apriori

inspect(reglas_importacion_apriori)
```
Reglas de asociación FP-Growth
```{r}

data_importacion
datamsc <- data_importacion
datamsc1 <- datamsc[, c(1,2,4,5,6,7,8)]
reglas <- fim4r(datamsc1, method = "fpgrowth", target="rules", supp = .2, conf = .5)
reglasframe <- as(reglas, "data.frame")
reglasframe

datamsc2 <- subset(data_importacion, CONTINENTE != "América")
datamsc2 <-  datamsc2[, c(1,2,4,5,6,7,8)]
reglas2 <- fim4r(datamsc2, method = "fpgrowth", target="rules", supp = .2, conf = .5)
reglasframe2 <- as(reglas2, "data.frame")
reglasframe2

```

Análisis de clúster
```{r}
data_importacion
data_importacion_apriori = subset(data_importacion, select = -NOMBRE_PAIS)
data_importacion_apriori = subset(data_importacion_apriori, select = -CONTINENTE)
data_importacion_apriori = subset(data_importacion_apriori, select = -ANYO_MES)
reglas_importacion_apriori = apriori(data_importacion_apriori, parameter = list(support = 0.2, confidence = 0.5) )

inspect(reglas_importacion_apriori)

summary(data_importacion_apriori)

cluster <- kmeans(data_importacion_apriori, centers=3)

ggplot(data_importacion_apriori, aes(x = ADUANA, y = VALOR, color = as.factor(cluster$cluster)))+
  geom_point()+
  geom_point(data = as.data.frame(cluster$centers), aes(x=PAIS, y = VALOR), color = "black", size=4, shape=17)+
  labs(title = "ADUANA vs VALOR")+
  theme_minimal()


ggplot(data_importacion_apriori, aes(x = ADUANA, y = VALOR, color = as.factor(cluster$cluster), shape = as.factor(cluster$cluster))) +
  geom_point(size = 3, alpha = 0.7) +  # Plot data points with alpha for transparency
  geom_point(data = as.data.frame(cluster$centers),  # Add cluster centers
             aes(x = ADUANA, y = VALOR), fill = c("yellow", "cyan", "magenta"), color = "black", size = 5, shape = 21) +
  scale_fill_manual(values = c("yellow", "cyan", "magenta")) +  # Assign colors for centroid fill
  geom_encircle(aes(group = cluster$cluster, fill = as.factor(cluster$cluster)), 
                alpha = 0.2, s_shape = 1, expand = 0.05) +  # Encircle each cluster
  scale_color_manual(values = c("red", "green", "blue")) +  # Custom colors for clusters
  scale_shape_manual(values = c(16, 17, 15)) +  # Custom shapes for clusters
  labs(title = "ADUANA vs VALOR", x = "ADUANA", y = "VALOR") +
  theme_minimal() +
  theme(
    plot.title = element_text(hjust = 0.5, face = "bold"),
    legend.position = "right",
    legend.title = element_blank()
  )

```
